openforge/JuntoScope

src/app/app.module.ts, src/app/http.interceptor.ts, src/environments/environment.ts
Added a http interceptor to look into the request url and if is a cloud function request will add the firebase token
=> feat(): Added http interceptor

src/app/authentication/containers/login/login.component.html, src/app/authentication/containers/login/login.component.ts, src/app/authentication/services/auth.service.ts, src/app/authentication/state/auth.facade.ts
- Add Facebook button as an option to log in.
- Adjust language in the HTML template to match the current mockup.
- Hook into click function inside the login component.
- Add dispatch action to call login service specifically for Facebook.
- Add an extra case to the switch in the login logic inside the auth service to execute firebase facebook login.
=> feat(authentication): Facebook Authentication

functions/src/api/connections/add-connection.ts, package.json, src/app/connections/state/connection.facade.ts, src/app/shared/popup.service.ts
This PR adds extra data on the response when adding a new connection and the alert after add the connection
=> feat: Add modal when adding connection

package.json, src/app/dashboard/components/session-detail-modal/session-detail-modal.component.html, src/app/dashboard/components/session-detail-modal/session-detail-modal.component.ts, src/app/dashboard/components/session-history-item/session-history-item.component.html, src/app/dashboard/container/dashboard/dashboard.component.ts, src/app/dashboard/services/history.service.ts, src/app/dashboard/state/dashboard.actions.ts, src/app/dashboard/state/dashboard.facade.ts
This PR adds functionality to refresh the expiration date for the access code of the session
=> feat: Add refesh code

functions/src/api/session-links/delete-session.ts, functions/src/api/session-links/index.ts, functions/src/services/session.service.ts, package.json, src/app/dashboard/components/session-detail-modal/session-detail-modal.component.html, src/app/dashboard/components/session-detail-modal/session-detail-modal.component.ts, src/app/dashboard/services/history.service.ts, src/app/dashboard/state/dashboard.actions.ts, src/app/dashboard/state/dashboard.facade.ts
This PR adds the functionality to delete a session from the dashboard only for Moderators
=> feat: Add delete session

src/features/authentication/pages/login/login.ts
=> fix(): fix ticket #46

src/features/dashboard/components/session-history-item/session-history-item.component.html
This PR fix the format of the history item in a simpler way
=> fix(history-item): fix the time format

src/features/connections/components/connection-list/connection-list.component.html, src/features/connections/pages/connection-details/connection-details.component.html, src/features/settings/pages/settings/settings.html
=> fix(): fix issue 52

src/features/authentication/pages/login/login.ts
This PR fix the auth login redirect, now instead of just going to dashboard we are waiting to the authenticated action to go to dashboard.
I know it's little hack so let me know your thoughts.
=> fix(login): fix login redirect

src/features/dashboard/components/session-history-item/session-history-item.component.html
This PR fix the ticket #69 fixing the format to display the date.
=> fix(): fix ticket 69

src/features/connections/pages/share-scope-link/share-scope-link.component.html, src/features/connections/pages/share-scope-link/share-scope-link.component.scss, src/features/connections/pages/share-scope-link/share-scope-link.component.ts
This PR fix the ticket #74 adding a back button at the header to go to dashboard page
=> fix(): fix ticket 74

src/features/connections/pages/add-connection/add-connection.component.ts, src/features/connections/store/connection.actions.ts, src/features/connections/store/connection.facade.ts
=> fix(): fix ticket 71

src/features/authentication/pages/login/login.ts, src/features/dashboard/pages/dashboard/dashboard.component.html
This PR fix the issue #67 related to the back button on the dashboard page
=> fix(): fix ticket 67

config.xml, package.json, src/app/app.component.ts, src/app/app.module.ts
=> fix(): fix ticket 75

src/features/connections/pages/add-connection/add-connection.component.html, src/features/connections/pages/add-connection/add-connection.component.scss, src/features/scoping/components/session-access/session-access.component.html, src/features/scoping/components/session-access/session-access.component.scss, src/features/scoping/components/vote/vote.component.html
style(session-access): add styles for component
fix(vote): center input text per QA notes
style(add-connection): update input and error styles to match
=> add-connection, session-access, and vote frontend fixes from QA

src/features/scoping/components/session-access/session-access.component.ts, src/features/scoping/store/scoping.facade.ts
@PaulPaulDevelops i got you covered, this PR fix the problem with the error and multiple popups #103.
The problem wasn't the error not cleaned, was the subscription that wasn't removed so every time we try to join, we add new subscriber so.. that's why appears every time one popup more.
=> fix(): fix ticket 103

src/features/connections/pages/connection-details/connection-details.component.ts
This PR fix the issue that mention @Wholloran on the ticket #65 about the white page going back.
=> fix(): fix issue 65

src/features/dashboard/pages/dashboard/dashboard.component.html, src/features/dashboard/pages/dashboard/dashboard.component.scss
This PR moves the infinite scroll spinner to the default place at the bottom.
=> fix(): fix infinite scroll

src/features/scoping/components/counted-votes/counted-votes.component.html, src/features/scoping/components/counted-votes/counted-votes.component.scss, src/features/scoping/components/select-result/select-result.component.html, src/features/scoping/components/select-result/select-result.component.scss, src/features/scoping/pages/session-scoping/session-scoping.component.html, src/features/scoping/pages/task-results/task-results.component.html
I updated the styles within the flow per #90 entails. In addition, I updated the static votes component for it to not only look similar to the style above to the result page but in the case of 3+ votes, I have it wrapped to the next line.
=> PR #90 Update Scoping Flow Styles

src/features/connections/pages/select-task-list/select-task-list.component.ts, src/shared/loading.service.ts
I notified that when trying to create a session i was getting an error with the loading service, i just added a check to avoid errors. Also added the loading on that flow so we show the loading while is creating the session and then we show the modal to start the session.
=> fix(): fix loading service

src/features/scoping/components/vote/vote.component.ts
This PR sets the minimum of the estimate vote to 0.5 as per discussion with @daftclaud @Wholloran
=> Fix min vote

src/features/scoping/pages/session-scoping/session-scoping.component.html, src/features/scoping/pages/session-scoping/session-scoping.component.ts
This fix didn't go on the Android release so we should merge this after the iOS release in order to have the same code in both releases and then, in the next update merge this and release both apps with the fix. What do you think @Wholloran?
=> fix(): fix ticket 134

package-lock.json, src/features/authentication/pages/login/login.component.ts, src/features/connections/pages/add-connection/add-connection.component.ts, src/features/connections/pages/select-task-list/select-task-list.component.ts, src/shared/loading.service.ts
The cause of this issue was the loading object being created on the loading service. It became
unavailable after it was destroyed.
#158
=> fix(login): handles loging in and out

README.md
This PR updates the README to cover all the configuration and set up flows (#178).
=> fix(readme): update readme file
